version: '2'  
services:  

  broker:
    image: rabbitmq:3
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
#    volumes:
#      - ./data/rabbitmq:/var/lib/rabbitmq:rw
#      - ./config/rabbitmq/definitions.json:/opt/definitions.json:ro
#      - ./config/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

  redis:
    image: redis:alpine
    restart: always
#    volumes:
#      - ./data/redis/:/data:rw

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./data/mongo/db:/data/db:rw
      - ./data/mongo/configdb:/data/configdb:rw

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./code:/code
      - ./config/nginx:/etc/nginx/conf.d

  web:
    build: .
    restart: always
    command: bash -c "python manage.py makemigrations && python manage.py migrate && uwsgi --http :8000 --http-websockets --gevent 1000 --master --ini uwsgi.ini"
    volumes:
      - ./code:/code
    ports:
      - "8080:8000"
    depends_on:
      - broker
      - redis
      - mongo
      - nginx      

  mainworker:
    build: .
    restart: always
    command: celery -A remotelogger worker --autoscale=3,1 -Q celery -l INFO -E --hostname=mainworker@%h -P gevent --uid celery --gid celery
    volumes:
      - ./code:/code
    depends_on:
      - broker
      - redis

  consumerworker:
    build: .
    restart: always
    command: celery -A remotelogger worker --autoscale=8,4 -Q consumer -l INFO -E --hostname=consumerworker@%h -P gevent --uid celery --gid celery
    volumes:
      - ./code:/code
    depends_on:
      - broker
      - redis
      - mongo
